version: "3"

services:
  app:
    build: .
    container_name: fastapi-book-app
    expose:
      - "8000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: fastapi-nginx-server
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"    # Changed from 80:80
      - "8443:443"   # Changed from 443:443
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
